import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

WEBSOCKET_HOST = os.getenv("WEBSOCKET_HOST", "0.0.0.0")
WEBSOCKET_PORT = int(os.getenv("WEBSOCKET_PORT", 8765))

KEYPOINT_BUFFER_SIZE = 32
SLIDING_WINDOW_SIZE = 5

THROTTLE_MIN_INTERVAL_MS = 75
THROTTLE_PROBABILITY_THRESHOLD = 0.03

MEDIAPIPE_MODEL_COMPLEXITY = 1
MEDIAPIPE_MIN_DETECTION_CONFIDENCE = 0.5
MEDIAPIPE_MIN_TRACKING_CONFIDENCE = 0.5
MEDIAPIPE_MAX_NUM_HANDS = 2

NUM_HANDS = 2
HAND_LANDMARKS = 21
COORDS_PER_LANDMARK = 3
TOTAL_LANDMARKS = HAND_LANDMARKS * NUM_HANDS
LSTM_INPUT_DIM = TOTAL_LANDMARKS * COORDS_PER_LANDMARK

LSTM_MODEL_PATH = BASE_DIR / "models" / "lstm_model.pt"
LSTM_HIDDEN_SIZE = 128
LSTM_NUM_LAYERS = 2
LSTM_NUM_CLASSES = 26

THREAD_POOL_MAX_WORKERS = 4

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
